version: "3.8"

services:

  static_app:
    build: ./static_web/
    labels:
      # HTTPS
      - "traefik.http.routers.static_web.rule=Host(`localhost`)"
      - "traefik.http.routers.static_web.entrypoints=websecure"
      - "traefik.http.routers.static_web.tls=true"
      - "traefik.http.routers.static_web.middlewares=sts@file"

  todo_api:
    build: ./todo_api/
    deploy:
      replicas: 2
    labels:
      - "traefik.http.services.todo_api.loadbalancer.server.port=7070"

      ## Sticky session
      - "traefik.http.services.todo_api.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.todo_api.loadbalancer.sticky.cookie.name=todo_api_sticky"
      - "traefik.http.services.todo_api.loadbalancer.sticky.cookie.secure=true"
      - "traefik.http.services.todo_api.loadbalancer.sticky.cookie.httpOnly=true"

      # HTTPS
      - "traefik.http.routers.todo_api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo_api.entrypoints=websecure"
      - "traefik.http.routers.todo_api.tls=true"
      - "traefik.http.routers.todo_api.middlewares=todo_api_stripprefix@file,sts@file"

  reverse_proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Mounts the volume to persist certificates
      - ./certs:/etc/traefik/certificates
      # Mounts the volume to the traefik conf files
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/dyn.yaml:/etc/traefik/dyn.yaml

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  data:
