version: "3.8"

services:
  todo_api:
    build: ./todo_api/
    labels:
      - "traefik.http.routers.todo_api.rule=Host(`todo_api.docker.localhost`)"
      - "traefik.http.services.todo_api.loadbalancer.server.port=7070"

  static_app:
    build: ./static_web/
    labels:
      - "traefik.http.routers.static_web.rule=Host(`static_web.docker.localhost`)"

  reverse_proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock